### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by groyoh** [GringerApps/minimalin#69]
This issue is meant to keep track of all feature requests that we receive:

**Highest priority:**
- [x] Prevent the weather and date to be hidden by the hands #68
- [x] Aplite compatibilty #31 
- [x] Make sure every configuration item is visible on small devices (https://goo.gl/ojt3Xi)

**Medium priority:**
- [x] Better description of the fixed location (https://goo.gl/Z6W7XJ)
- [x] Steps and sleep (Pebble Health integration)
- [ ] ~~Possibility to choose a bigger font size~~
- [x] Low battery warning

**Lower priority:**
- [ ] ~~Different color configuration for the hour and minute ticks (https://goo.gl/8joRFJ)~~
- [x] 24-hour option
- [ ] ~~Possibility to opt-in for displaying ticks for every 1 or 5 minutes~~
- [ ] ~~Bluetooth icon visible when connected and hidden otherwise~~
- [ ] ~~Add high/low temperature for the day~~
- [x] Vibration every full hour
- [ ] Show sleep in the morning (Pebble Health)

**Comment by juanpg** [comment]
Add Weather Underground / forecast.io as weather sources, allowing the user to enter their own key.

**Comment by hate-picking-names** [comment]
Instead of showing ticks for hour and minute, I would like to see ticks for hour and next hour. You could also highlight the current hour or maybe the closest hour.
![watchfaceidea](https://cloud.githubusercontent.com/assets/18424678/14467262/1e7abfc4-00a0-11e6-9b5f-3ee1f3dad172.jpg)

**Comment by marcteys** [comment]
I'll try to work on the preview layout and also add a feature to select within some theme presets.

**Comment by AlessioLaiso** [comment]
@groyoh: I've tweaked your opening post to organize the features based on priority. Feel free to edit/discuss!

**Comment by groyoh** [comment]
@juanpg how would that be better than the current implementation with OpenWeatherMap?

**Comment by groyoh** [comment]
> Instead of showing ticks for hour and minute, I would like to see ticks for hour and next hour. You could also highlight the current hour or maybe the closest hour.

@hate-picking-names thanks for the idea.
@AlessioLaiso what do you think about that?

**Comment by juanpg** [comment]
@groyoh Accuracy and personal preference basically.

**Comment by AlessioLaiso** [comment]
@hate-picking-names @groyoh: I think the idea makes sense in its own, we just need to make sure that the configuration page doesn't become too complicated/confusing, also because things like these are not super easy to explain in a sentence. Let's keep it in mind and see what we can do!

**Comment by groyoh** [comment]
> Accuracy

@juanpg Anything wrong with OpenWeatherMap accuracy?

> and personal preference basically.

@juanpg Not really an argument :wink: 

>  I think the idea makes sense in its own, we just need to make sure that the configuration page doesn't become too complicated/confusing

@AlessioLaiso good point. @hate-picking-names maybe you could help us find the best way to show/display such feature in the configuration.

**Comment by bmedicke** [comment]
I would prefer different colours for the bluetooth icon and the weather info.

**Comment by hate-picking-names** [comment]
@groyoh are you just looking for wording or are you looking for more specifics like list selector vs radio buttons and/or display?

**Comment by groyoh** [comment]
@hate-picking-names We will likely have to rethink a lot of the configuration page when the new features are released, so I guess it probably makes more sense to wait and see what happens by then. At the moment, I think wording could be a good beginning.

**Comment by hate-picking-names** [comment]
@groyoh Maybe something like:
Ticks to Display: 
- Current Hour and Current Minute
- Current Hour and Next Hour

**Comment by groyoh** [comment]
@hate-picking-names the issue I see here is: what if somebody wants the current hour, next hour and still keep the minute one? Or the minute and the next tick for the minute?

**Comment by hate-picking-names** [comment]
@groyoh Fair enough. Maybe you just have a toggle to enable each option independently? Then you can pick whatever combination you want. Maybe also one to show ticks but no number or just a three-option list selector?
I realize this is already starting to get ridiculous.

**Comment by beatles1** [comment]
Love the watch face. Just a couple of thing's I'd love to see.

- Battery Indicator
Personally I do like to be able to check to the nearest 10% with a glance so I get reminded to top it up if I'm about to go away but even just a 100%/50%/20% icon would be fantastic as I can see anything more detailed not fitting this face.

- Day of the week
Having Mon/Tue etc in front of the date would be really useful for people with terrible memory like me!

**Comment by marcteys** [comment]
Well... You'll have to make à design choice, which is not so easy ...

Eigther you follow everyone's suggestions and add a lot of configuration possibilities (each icon could be customiable), or eigther you make some strong Design choices, and don't let the user choosing everything.

It's up to you

**Comment by groyoh** [comment]
@marcteys we are mainly taking ideas and then figuring out if (and how) it could fit into minimalin. There are features that were already planned and that will be kept for sure (e.g. high and medium priorities). Other things that does not need to touch the configuration will most likely go in too (e.g. 24-hour format).

**Comment by marcteys** [comment]
Your list sounds great. Critical problems needs to be fixed first.

 I will have some work to do to help thought. :D

**Comment by Spitemare** [comment]
For the small devices issue, it might be an older Android Jelly Bean [problem](https://groups.google.com/forum/#!topic/phonegap/1Tg_1T_c1ac). 4.3 and previous seem to have some issues with position:fixed. The device in question shipped with Android 4.3.

Possible fix might be to include a meta tag indicating a non-scalable viewport.

**Comment by marcteys** [comment]
@spitemare @groyoh : I'm fixing that

**Comment by groyoh** [comment]
@Spitemare thanks for the info. I have to admit that I'm a freaking noob in frontend :grin: 

@marcteys that's awesome. Thanks! :tada:

**Comment by phm3** [comment]
Any chance to add font selection or/and its size (in some reasonable range)?

**Comment by groyoh** [comment]
@phm3 that's not feasible at the moment. We built a custom font with fixed sized. @AlessioLaiso would have to rework the font in order to do so.

**Comment by AlessioLaiso** [comment]
@phm3 @groyoh The font will need some love anyway when we'll add steps, so let's see what we can do here.

**Comment by datrizal** [comment]
i really hope this watchface could show me my sleep result in the morning, btw, this is super cool watchface. thanks!

**Comment by michou** [comment]
How about **not** hiding the weather when the update fails?

I'll try whipping up a PR for this one, but if not, maybe you can get to it 😁

**Comment by AlessioLaiso** [comment]
@michou: feel free to open an issue, where we'll be able to discuss the best way to implement this.

**Comment by zhoueysun** [comment]
1. I also vote day of the week option
2. Full 4 digit 24 hour clock display at end of hour hand rather than split. Then I only need to look at one place

**Comment by groyoh** [comment]
@zhoueysun I think we won't implement your second idea as the current implementation is the core design of minimalin. As for the day of the week, we're going to release a big update this week. We'll consider that feature afterward.

**Comment by hkawaji** [comment]
Very cool watch face. It would be great to have a feature - vibration when bluetooth connection broken.

**Comment by adduc** [comment]
@groyoh You might be able to speed up the Travis builds by switching to a docker image with the SDK pre-installed (e.g. [adduc/debian-pebble](https://hub.docker.com/r/adduc/debian-pebble/)). I've been able to get builds (granted, of a less complex [watchface](https://gitlab.128.io/adduc/pebble-first-watchface)) with screenshots running in ~35 seconds.

**Comment by groyoh** [comment]
@adduc thanks for the idea :+1:

**Comment by lfoma** [comment]
Thanks for great watchface! This is what i have been imagine since get my PTR;
My idea is just add twelve hours dots at the screen, but only active hour\minute have digit;
Without dots its pretty hard to understand ticks in open space.

**Comment by PotatoFi** [comment]
This is by far my favorite watchface, period. Where is the config page hosted? Would it be possible to convert it to [Clay](https://github.com/pebble/clay), so that there is no danger of the config page becoming inaccessible when Pebble services begin to go offline?

**Comment by groyoh** [comment]
@lfoma thanks for reaching out to us but since Pebble is on the way out, we decided that we won't spend more time on watchfaces until we get further news from Fitbit.
@PotatoFi  don't worry. The config page is a static web page hosted via rawgit. As long as rawgit will live, minimalin will too. Also, in case you did not know, Clay depends on pebble's S3 account (https://github.com/pebble/clay/blob/master/index.js#L177). So watchfaces using it propably won't work any longer if it gets shut down.

**Comment by 123qwe33** [comment]
Did the settings page recently stop working?

**Comment by groyoh** [comment]
@123qwe33 Yes. The settings page was hosted via rawgit.com which stopped their service around 2021 I believe. And since Pebble was no longer officially maintained at that point, I never took the time to fix this issue.

**Comment by 123qwe33** [comment]
I've got a small vps web server, would it be something I could host? This is my favorite watchface, I'd love to help out with supporting it

**Comment by 123qwe33** [comment]
@groyoh Hey, I just got the settings page here: https://minimalin.geoff.design/

To point the watchface at the new settings page would I just change "https://cdn.rawgit.com/groyoh/minimalin/ffd0da5fb45f0722dee6e59eb4b05fa63ca82136/config/index.html" to my URL in app.js? I can create an issue and a pull request potentially if that's cool with you?

I can put it at a different URL too, that was just the easiest place for me to get it up quickly.
